(function () {
  const colorSets = {
    angkoraSprayer: [
      { label: "បៃតង", hex: "#5fd3cd" },
      { label: "ស", hex: "#f5f7f7" },
      { label: "ទឹកក្រូច", hex: "#ff7a45" },
    ],
    nikazaSprayer: [
      { label: "ខៀវ", hex: "#8ec5df" },
      { label: "ស", hex: "#f5f7f7" },
      { label: "បៃតង", hex: "#7ecfb3" },
    ],
    angkoraBattery: [
      { label: "ខៀវស្រាល", hex: "#8ec5df" },
      { label: "ទឹកក្រូច", hex: "#ff8453" },
      { label: "ខ្មៅ", hex: "#22343a" },
    ],
    nikazaBattery: [
      { label: "ខៀវ", hex: "#a5b2ef" },
      { label: "ផ្កាឈូក", hex: "#e2a0bd" },
      { label: "ខ្មៅ", hex: "#22343a" },
    ],
    superbatBattery: [
      { label: "លឿង", hex: "#e9cb62" },
      { label: "ខ្មៅ", hex: "#222e34" },
      { label: "ស", hex: "#f7f7f5" },
    ],
    mister: [
      { label: "បៃតង", hex: "#9ed5aa" },
      { label: "ស", hex: "#f7f7f5" },
      { label: "ទឹកក្រូច", hex: "#ff7a45" },
    ],
  };

  function getSizes(product) {
    if (product.similarKey === "battery") {
      return [product.volume, "ថាមពលចល័ត"];
    }

    if (product.similarKey === "mister") {
      return [product.volume, "បាញ់អ័ព្ទ"];
    }

    return [product.volume, "ស្ពាយក្រោយ"];
  }

  function makeProduct(definition) {
    const tags = definition.tags ?? [];

    return {
      ...definition,
      colors: definition.colors ?? colorSets[definition.colorGroup] ?? [],
      sizes: definition.sizes ?? getSizes(definition),
      searchText: [
        definition.code,
        definition.brand,
        definition.volume,
        definition.series,
        definition.title,
        definition.description,
        ...tags,
      ]
        .join(" ")
        .toLowerCase(),
      tags,
    };
  }

  const products = [
    makeProduct({
      code: "AGT-767",
      brand: "Angkora",
      filterType: "sprayer",
      similarKey: "sprayer",
      icon: "sprayer",
      volume: "25L",
      title: "ម៉ាស៊ីនបាញ់ស្ពាយក្រោយ អង្គរា",
      description: "ម៉ូដែលតូចងាយប្រើ សមស្របសម្រាប់បាញ់ថ្នាំសួនច្បារ និងការងារប្រចាំថ្ងៃ។",
      series: "Classic",
      depoPrice: "$69.50",
      userPrice: "$92.00",
      stock: 34,
      featured: true,
      artBg: "#eefbf6",
      artColor: "#89d8c2",
      colorGroup: "angkoraSprayer",
      tags: ["featured", "sprayer", "angkora", "agt-767", "25l", "backpack"],
    }),
    makeProduct({
      code: "AGT-808",
      brand: "Angkora",
      filterType: "sprayer",
      similarKey: "sprayer",
      icon: "sprayer",
      volume: "25L",
      title: "ម៉ាស៊ីនបាញ់ស្ពាយក្រោយ អង្គរា",
      description: "ស៊ុមមានតុល្យភាពល្អ សម្រាប់ការបាញ់ថ្នាំបានស្មើគ្នានៅក្នុងសួន និងចម្ការ។",
      series: "Standard",
      depoPrice: "$69.50",
      userPrice: "$92.00",
      stock: 18,
      artBg: "#f7f5ee",
      artColor: "#dac9b1",
      colorGroup: "angkoraSprayer",
      tags: ["sprayer", "angkora", "agt-808", "25l", "backpack", "orange"],
    }),
    makeProduct({
      code: "NK-767",
      brand: "Nikaza",
      filterType: "sprayer",
      similarKey: "sprayer",
      icon: "sprayer",
      volume: "25L",
      title: "ម៉ាស៊ីនបាញ់ស្ពាយក្រោយ នីកាហ្សា",
      description: "ម៉ូដែលពេញនិយមសម្រាប់អ្នកលក់ ដោយមានប្លង់បញ្ជាច្បាស់ និងមូលដ្ឋានរឹងមាំ។",
      series: "Farm Core",
      depoPrice: "$65.50",
      userPrice: "$87.00",
      stock: 27,
      featured: true,
      artBg: "#edf8ff",
      artColor: "#9fcfe9",
      colorGroup: "nikazaSprayer",
      tags: ["featured", "sprayer", "nikaza", "nk-767", "25l", "backpack"],
    }),
    makeProduct({
      code: "NK-808",
      brand: "Nikaza",
      filterType: "sprayer",
      similarKey: "sprayer",
      icon: "sprayer",
      volume: "25L",
      title: "ម៉ាស៊ីនបាញ់ធុនធ្ងន់ នីកាហ្សា",
      description: "រចនាសម្រាប់ការងារយូរជាងមុន ដោយមានរាងស្ថិរភាព និងផ្នែកម៉ូទ័ររឹងមាំ។",
      series: "Standard",
      depoPrice: "$65.50",
      userPrice: "$87.00",
      stock: 9,
      artBg: "#f1fbf8",
      artColor: "#94d5bf",
      colorGroup: "nikazaSprayer",
      tags: ["sprayer", "nikaza", "nk-808", "25l", "backpack"],
    }),
    makeProduct({
      code: "NK-1390FH",
      brand: "Nikaza",
      filterType: "sprayer",
      similarKey: "sprayer",
      icon: "sprayer",
      volume: "26L",
      title: "ម៉ាស៊ីនបាញ់ នីកាហ្សា ម៉ូដែល ១៣៩០",
      description: "ចំណុះធំ សម្រាប់បាញ់បានទូលំទូលាយ និងងាយស្រួលផ្លាស់ទីនៅក្នុងចម្ការ។",
      series: "Pro Line",
      depoPrice: "$77.50",
      userPrice: "$103.00",
      stock: 7,
      artBg: "#fff4ec",
      artColor: "#f7c29d",
      colorGroup: "nikazaSprayer",
      tags: ["sprayer", "nikaza", "nk-1390fh", "26l", "portable"],
    }),
    makeProduct({
      code: "AGT-777",
      brand: "Angkora",
      filterType: "sprayer",
      similarKey: "sprayer",
      icon: "sprayer",
      volume: "28L",
      title: "ម៉ាស៊ីនបាញ់ អង្គរា ម៉ូដែល ៧៧៧",
      description: "ម៉ូដែលចំណុះខ្ពស់ សម្រាប់ផ្ទៃដីធំ និងកាត់បន្ថយការបញ្ចូលទឹកញឹកញាប់។",
      series: "Max Tank",
      depoPrice: "$69.50",
      userPrice: "$92.00",
      stock: 16,
      artBg: "#f3efff",
      artColor: "#c2b2ee",
      colorGroup: "angkoraSprayer",
      tags: ["sprayer", "angkora", "agt-777", "28l", "backpack"],
    }),
    makeProduct({
      code: "AGT-20M",
      brand: "Angkora",
      filterType: "battery",
      similarKey: "battery",
      icon: "battery",
      volume: "20L",
      title: "ឧបករណ៍បាតឺរី អង្គរា",
      description: "ឧបករណ៍ថាមពលចល័ត សម្រាប់ការងារបាញ់ថ្នាំ និងរក្សាទុកបានងាយស្រួល។",
      series: "Mobile Pack",
      depoPrice: "$25.00",
      userPrice: "$37.00",
      stock: 21,
      featured: true,
      artBg: "#eef9ff",
      artColor: "#8ec5df",
      colorGroup: "angkoraBattery",
      tags: ["featured", "battery", "angkora", "agt-20m", "20l", "portable"],
    }),
    makeProduct({
      code: "AGT-20LR",
      brand: "Angkora",
      filterType: "battery",
      similarKey: "battery",
      icon: "battery",
      volume: "20L",
      title: "ឧបករណ៍សាកថ្ម អង្គរា",
      description: "បាតឺរីចល័តទម្ងន់ស្រាល សមស្របសម្រាប់ការងារលើផ្ទៃតូច និងប្រើប្រាស់បានបត់បែន។",
      series: "LR Pack",
      depoPrice: "$26.80",
      userPrice: "$40.00",
      stock: 14,
      artBg: "#fff8ec",
      artColor: "#ebc782",
      colorGroup: "angkoraBattery",
      tags: ["battery", "angkora", "agt-20lr", "20l", "rechargeable"],
    }),
    makeProduct({
      code: "NK-8000",
      brand: "Nikaza",
      filterType: "sprayer",
      similarKey: "mister",
      icon: "mister",
      volume: "Pro",
      title: "ម៉ាស៊ីនបាញ់អ័ព្ទ នីកាហ្សា",
      description: "ម៉ូដែលក្បាលមូល សម្រាប់បាញ់ផ្សាយបានទូលំទូលាយ និងងាយប្រើនៅកន្លែងចង្អៀត។",
      series: "NK 8000",
      depoPrice: "$83.00",
      userPrice: "$110.00",
      stock: 5,
      artBg: "#f1f9f4",
      artColor: "#9ed5aa",
      colorGroup: "mister",
      sizes: ["Pro", "បាញ់អ័ព្ទ"],
      tags: ["sprayer", "nikaza", "nk-8000", "mister"],
    }),
    makeProduct({
      code: "NK-20L",
      brand: "Nikaza",
      filterType: "battery",
      similarKey: "battery",
      icon: "battery",
      volume: "V8 AH",
      title: "ប្រអប់បាតឺរី នីកាហ្សា",
      description: "ប្រអប់ថាមពលតូច សម្រាប់ភ្ជាប់ជាមួយប្រព័ន្ធបាញ់ថ្នាំកសិកម្មចល័ត។",
      series: "Power Box",
      depoPrice: "$22.00",
      userPrice: "$33.00",
      stock: 11,
      artBg: "#eef2ff",
      artColor: "#a5b2ef",
      colorGroup: "nikazaBattery",
      sizes: ["V8 AH", "ថាមពលចល័ត"],
      tags: ["battery", "nikaza", "nk-20l", "20l", "v8", "ah"],
    }),
    makeProduct({
      code: "NK-20LR",
      brand: "Nikaza",
      filterType: "battery",
      similarKey: "battery",
      icon: "battery",
      volume: "V8 AH",
      title: "ប្រអប់បាតឺរីសាកថ្ម នីកាហ្សា",
      description: "ប្រអប់សាកថ្មចល័ត រចនាតូចសមរម្យសម្រាប់ការដាក់បង្ហាញក្នុងកាតាឡុក។",
      series: "Power Box LR",
      depoPrice: "$22.00",
      userPrice: "$33.00",
      stock: 6,
      artBg: "#f9eef4",
      artColor: "#e2a0bd",
      colorGroup: "nikazaBattery",
      sizes: ["V8 AH", "ថាមពលចល័ត"],
      tags: ["battery", "nikaza", "nk-20lr", "20l", "v8", "ah"],
    }),
    makeProduct({
      code: "SP-20L",
      brand: "Superbat",
      filterType: "battery",
      similarKey: "battery",
      icon: "battery",
      volume: "12V 8AH",
      title: "ឧបករណ៍បាតឺរី ស៊ុបឺបេត",
      description: "ម៉ូដែលបាតឺរីរឹងមាំ ពណ៌ភ្លឺ សម្រាប់ការងារចល័ត និងសាកថ្មម្តងហើយម្តងទៀត។",
      series: "Super Power",
      depoPrice: "$19.20",
      userPrice: "$28.00",
      stock: 24,
      featured: true,
      artBg: "#fff9e7",
      artColor: "#e9cb62",
      colorGroup: "superbatBattery",
      sizes: ["12V 8AH", "ថាមពលចល័ត"],
      tags: ["featured", "battery", "superbat", "sp-20l", "12v", "8ah"],
    }),
    makeProduct({
      code: "AGT-909",
      brand: "Angkora",
      filterType: "sprayer",
      similarKey: "sprayer",
      icon: "sprayer",
      volume: "18L",
      title: "ម៉ាស៊ីនបាញ់ស្ពាយក្រោយ អង្គរា",
      description: "ម៉ូដែលចំណុះ ១៨ លីត្រ សម្រាប់ការបាញ់ថ្នាំបានរហ័ស និងងាយស្រួលប្រើ។",
      series: "Eco Flow",
      depoPrice: "$58.00",
      userPrice: "$78.00",
      stock: 22,
      featured: true,
      artBg: "#eefbf6",
      artColor: "#82d7be",
      colorGroup: "angkoraSprayer",
      tags: ["featured", "sprayer", "angkora", "agt-909", "18l", "backpack", "eco"],
    }),
    makeProduct({
      code: "AGT-918",
      brand: "Angkora",
      filterType: "sprayer",
      similarKey: "sprayer",
      icon: "sprayer",
      volume: "20L",
      title: "ម៉ាស៊ីនបាញ់ស្ពាយក្រោយ អង្គរា",
      description: "សាកសមសម្រាប់សួនបន្លែ និងចម្ការតូច ដោយមានទម្ងន់ស្រាល និងងាយបញ្ជា។",
      series: "Field Start",
      depoPrice: "$60.00",
      userPrice: "$82.00",
      stock: 19,
      artBg: "#f5fbef",
      artColor: "#b3d97a",
      colorGroup: "angkoraSprayer",
      tags: ["sprayer", "angkora", "agt-918", "20l", "backpack", "field"],
    }),
    makeProduct({
      code: "AGT-928",
      brand: "Angkora",
      filterType: "sprayer",
      similarKey: "sprayer",
      icon: "sprayer",
      volume: "22L",
      title: "ម៉ាស៊ីនបាញ់ស្ពាយក្រោយ អង្គរា",
      description: "ស៊ុមរឹងមាំ និងបាញ់បានស្មើគ្នា សម្រាប់ការងារកសិកម្មប្រចាំថ្ងៃ។",
      series: "Garden Pro",
      depoPrice: "$63.50",
      userPrice: "$85.00",
      stock: 13,
      artBg: "#edf8ff",
      artColor: "#8dc4e2",
      colorGroup: "angkoraSprayer",
      tags: ["sprayer", "angkora", "agt-928", "22l", "backpack", "garden"],
    }),
    makeProduct({
      code: "AGT-938",
      brand: "Angkora",
      filterType: "sprayer",
      similarKey: "sprayer",
      icon: "sprayer",
      volume: "25L",
      title: "ម៉ាស៊ីនបាញ់ស្ពាយក្រោយ អង្គរា",
      description: "រចនាសម្រាប់ការប្រើប្រាស់យូរ ដោយមានខ្សែស្ពាយស្រួលស្មា និងធុងរឹងមាំ។",
      series: "Farm Lift",
      depoPrice: "$66.00",
      userPrice: "$88.00",
      stock: 8,
      artBg: "#fff5ed",
      artColor: "#efb489",
      colorGroup: "angkoraSprayer",
      tags: ["sprayer", "angkora", "agt-938", "25l", "backpack", "farm"],
    }),
    makeProduct({
      code: "AGT-948",
      brand: "Angkora",
      filterType: "sprayer",
      similarKey: "sprayer",
      icon: "sprayer",
      volume: "16L",
      title: "ម៉ាស៊ីនបាញ់ស្ពាយក្រោយ អង្គរា",
      description: "ម៉ូដែលតូច សម្រាប់បាញ់ថ្នាំលើដំណាំ និងផ្កា នៅតំបន់ដែលត្រូវការចល័តលឿន។",
      series: "Quick Run",
      depoPrice: "$55.00",
      userPrice: "$74.00",
      stock: 15,
      artBg: "#f4efff",
      artColor: "#c4afe9",
      colorGroup: "angkoraSprayer",
      tags: ["sprayer", "angkora", "agt-948", "16l", "backpack", "quick"],
    }),
    makeProduct({
      code: "AGT-958",
      brand: "Angkora",
      filterType: "sprayer",
      similarKey: "sprayer",
      icon: "sprayer",
      volume: "20L",
      title: "ម៉ាស៊ីនបាញ់ស្ពាយក្រោយ អង្គរា",
      description: "បំពាក់ផ្នែកបាញ់មានសម្ពាធល្អ សម្រាប់កាត់បន្ថយពេលវេលាការងារនៅសួនធំ។",
      series: "Power Mist",
      depoPrice: "$62.00",
      userPrice: "$84.00",
      stock: 12,
      artBg: "#eef8f7",
      artColor: "#7ec8bf",
      colorGroup: "angkoraSprayer",
      tags: ["sprayer", "angkora", "agt-958", "20l", "backpack", "power"],
    }),
    makeProduct({
      code: "AGT-968",
      brand: "Angkora",
      filterType: "sprayer",
      similarKey: "sprayer",
      icon: "sprayer",
      volume: "24L",
      title: "ម៉ាស៊ីនបាញ់ស្ពាយក្រោយ អង្គរា",
      description: "ធុងចំណុះមធ្យម សមស្របសម្រាប់ចម្ការដែលត្រូវការបាញ់ជាបន្តបន្ទាប់។",
      series: "Agri Plus",
      depoPrice: "$64.50",
      userPrice: "$86.00",
      stock: 10,
      artBg: "#fff7ef",
      artColor: "#f0bb96",
      colorGroup: "angkoraSprayer",
      tags: ["sprayer", "angkora", "agt-968", "24l", "backpack", "agri"],
    }),
    makeProduct({
      code: "AGT-978",
      brand: "Angkora",
      filterType: "sprayer",
      similarKey: "sprayer",
      icon: "sprayer",
      volume: "26L",
      title: "ម៉ាស៊ីនបាញ់ស្ពាយក្រោយ អង្គរា",
      description: "សម្រាប់ផ្ទៃដីធំ ដោយមានធុងធំ និងងាយស្រួលបញ្ចូលទឹកឡើងវិញ។",
      series: "Max Reach",
      depoPrice: "$68.00",
      userPrice: "$91.00",
      stock: 4,
      artBg: "#edf2ff",
      artColor: "#9eb1ef",
      colorGroup: "angkoraSprayer",
      tags: ["sprayer", "angkora", "agt-978", "26l", "backpack", "max"],
    }),
    makeProduct({
      code: "AGT-988",
      brand: "Angkora",
      filterType: "sprayer",
      similarKey: "sprayer",
      icon: "sprayer",
      volume: "28L",
      title: "ម៉ាស៊ីនបាញ់ស្ពាយក្រោយ អង្គរា",
      description: "ម៉ូដែលធុងធំសម្រាប់ការបាញ់បានទូលំទូលាយ និងកាត់បន្ថយការឈប់បញ្ចូលទឹក។",
      series: "Turbo Tank",
      depoPrice: "$71.00",
      userPrice: "$95.00",
      stock: 3,
      artBg: "#eefbf2",
      artColor: "#94d6a5",
      colorGroup: "angkoraSprayer",
      tags: ["sprayer", "angkora", "agt-988", "28l", "backpack", "turbo"],
    }),
    makeProduct({
      code: "NK-909",
      brand: "Nikaza",
      filterType: "sprayer",
      similarKey: "sprayer",
      icon: "sprayer",
      volume: "18L",
      title: "ម៉ាស៊ីនបាញ់ស្ពាយក្រោយ នីកាហ្សា",
      description: "ម៉ូដែលស្រាល សម្រាប់ប្រើប្រាស់ប្រចាំថ្ងៃ និងងាយស្រួលថែទាំ។",
      series: "Core Flow",
      depoPrice: "$56.50",
      userPrice: "$76.00",
      stock: 25,
      featured: true,
      artBg: "#eef8ff",
      artColor: "#91c3ea",
      colorGroup: "nikazaSprayer",
      tags: ["featured", "sprayer", "nikaza", "nk-909", "18l", "backpack", "core"],
    }),
    makeProduct({
      code: "NK-918",
      brand: "Nikaza",
      filterType: "sprayer",
      similarKey: "sprayer",
      icon: "sprayer",
      volume: "20L",
      title: "ម៉ាស៊ីនបាញ់ស្ពាយក្រោយ នីកាហ្សា",
      description: "រចនាឡើងសម្រាប់ការបាញ់ស្មើគ្នា និងមានចំណុចកាន់ងាយប្រើ។",
      series: "Field Core",
      depoPrice: "$58.50",
      userPrice: "$79.00",
      stock: 17,
      artBg: "#f2fbf8",
      artColor: "#8fd3b8",
      colorGroup: "nikazaSprayer",
      tags: ["sprayer", "nikaza", "nk-918", "20l", "backpack", "field"],
    }),
    makeProduct({
      code: "NK-928",
      brand: "Nikaza",
      filterType: "sprayer",
      similarKey: "sprayer",
      icon: "sprayer",
      volume: "22L",
      title: "ម៉ាស៊ីនបាញ់ស្ពាយក្រោយ នីកាហ្សា",
      description: "សមស្របសម្រាប់អ្នកលក់ និងអ្នកប្រើ ដោយមានសមត្ថភាពបាញ់បានល្អ។",
      series: "Dealer Pro",
      depoPrice: "$61.00",
      userPrice: "$82.00",
      stock: 10,
      artBg: "#fff4ee",
      artColor: "#f0b89b",
      colorGroup: "nikazaSprayer",
      tags: ["sprayer", "nikaza", "nk-928", "22l", "backpack", "dealer"],
    }),
    makeProduct({
      code: "NK-938",
      brand: "Nikaza",
      filterType: "sprayer",
      similarKey: "sprayer",
      icon: "sprayer",
      volume: "24L",
      title: "ម៉ាស៊ីនបាញ់ស្ពាយក្រោយ នីកាហ្សា",
      description: "ធុងរឹងមាំ និងងាយស្រួលស្ពាយសម្រាប់ការងារក្នុងចម្ការធំ។",
      series: "Farm Strong",
      depoPrice: "$63.00",
      userPrice: "$85.00",
      stock: 6,
      artBg: "#f4f1ff",
      artColor: "#bda8ea",
      colorGroup: "nikazaSprayer",
      tags: ["sprayer", "nikaza", "nk-938", "24l", "backpack", "strong"],
    }),
    makeProduct({
      code: "NK-948",
      brand: "Nikaza",
      filterType: "sprayer",
      similarKey: "sprayer",
      icon: "sprayer",
      volume: "16L",
      title: "ម៉ាស៊ីនបាញ់ស្ពាយក្រោយ នីកាហ្សា",
      description: "ម៉ូដែលតូចសម្រាប់សួនផ្ទះ និងការបាញ់ថ្នាំលើផ្កា ឬដំណាំទំហំតូច។",
      series: "Mini Farm",
      depoPrice: "$54.00",
      userPrice: "$73.00",
      stock: 12,
      artBg: "#eef9ff",
      artColor: "#8ebddd",
      colorGroup: "nikazaSprayer",
      tags: ["sprayer", "nikaza", "nk-948", "16l", "backpack", "mini"],
    }),
    makeProduct({
      code: "NK-958",
      brand: "Nikaza",
      filterType: "sprayer",
      similarKey: "sprayer",
      icon: "sprayer",
      volume: "20L",
      title: "ម៉ាស៊ីនបាញ់ស្ពាយក្រោយ នីកាហ្សា",
      description: "មានសម្ពាធបាញ់ល្អ និងរចនាសម្រាប់ការងារបន្តបន្ទាប់បានយូរ។",
      series: "Green Shot",
      depoPrice: "$59.50",
      userPrice: "$80.00",
      stock: 14,
      artBg: "#eefbf6",
      artColor: "#8fd5be",
      colorGroup: "nikazaSprayer",
      tags: ["sprayer", "nikaza", "nk-958", "20l", "backpack", "green"],
    }),
    makeProduct({
      code: "NK-968",
      brand: "Nikaza",
      filterType: "sprayer",
      similarKey: "sprayer",
      icon: "sprayer",
      volume: "25L",
      title: "ម៉ាស៊ីនបាញ់ស្ពាយក្រោយ នីកាហ្សា",
      description: "ម៉ូដែលសម្រាប់ការងារធ្ងន់ ដែលអាចបាញ់បានទូលំទូលាយ និងមានស្ថេរភាព។",
      series: "Agro Force",
      depoPrice: "$66.50",
      userPrice: "$89.00",
      stock: 8,
      artBg: "#edf8ff",
      artColor: "#98cbe7",
      colorGroup: "nikazaSprayer",
      tags: ["sprayer", "nikaza", "nk-968", "25l", "backpack", "agro"],
    }),
    makeProduct({
      code: "NK-978",
      brand: "Nikaza",
      filterType: "sprayer",
      similarKey: "sprayer",
      icon: "sprayer",
      volume: "28L",
      title: "ម៉ាស៊ីនបាញ់ស្ពាយក្រោយ នីកាហ្សា",
      description: "ចំណុះធំ សម្រាប់ការងារចម្ការធំ និងកាត់បន្ថយការឈប់សម្រាកញឹកញាប់។",
      series: "Max Farm",
      depoPrice: "$69.00",
      userPrice: "$93.00",
      stock: 2,
      artBg: "#f7f5ee",
      artColor: "#d4c1a5",
      colorGroup: "nikazaSprayer",
      tags: ["sprayer", "nikaza", "nk-978", "28l", "backpack", "max"],
    }),
    makeProduct({
      code: "AGT-12M",
      brand: "Angkora",
      filterType: "battery",
      similarKey: "battery",
      icon: "battery",
      volume: "12L",
      title: "ឧបករណ៍បាតឺរី អង្គរា",
      description: "បាតឺរីចល័តទំហំតូច សម្រាប់ការប្រើប្រាស់ងាយស្រួល និងដឹកជញ្ជូនបានលឿន។",
      series: "Mini Power",
      depoPrice: "$18.50",
      userPrice: "$27.00",
      stock: 20,
      artBg: "#eef9ff",
      artColor: "#84bddb",
      colorGroup: "angkoraBattery",
      tags: ["battery", "angkora", "agt-12m", "12l", "portable", "power"],
    }),
    makeProduct({
      code: "AGT-16M",
      brand: "Angkora",
      filterType: "battery",
      similarKey: "battery",
      icon: "battery",
      volume: "16L",
      title: "ឧបករណ៍បាតឺរី អង្គរា",
      description: "សាកសមសម្រាប់ការងារលើផ្ទៃតូច និងរក្សាទុកបានងាយ។",
      series: "Flex Pack",
      depoPrice: "$21.00",
      userPrice: "$31.00",
      stock: 18,
      artBg: "#fff8ed",
      artColor: "#e7c27d",
      colorGroup: "angkoraBattery",
      tags: ["battery", "angkora", "agt-16m", "16l", "portable", "flex"],
    }),
    makeProduct({
      code: "AGT-18LR",
      brand: "Angkora",
      filterType: "battery",
      similarKey: "battery",
      icon: "battery",
      volume: "18L",
      title: "ឧបករណ៍បាតឺរីសាកថ្ម អង្គរា",
      description: "ប្រើប្រាស់បានបត់បែន និងងាយស្រួលសាកថ្មសម្រាប់ការងារប្រចាំថ្ងៃ។",
      series: "LR Green",
      depoPrice: "$23.00",
      userPrice: "$34.00",
      stock: 9,
      artBg: "#eef4ff",
      artColor: "#9eadf0",
      colorGroup: "angkoraBattery",
      tags: ["battery", "angkora", "agt-18lr", "18l", "rechargeable", "lr"],
    }),
    makeProduct({
      code: "AGT-24M",
      brand: "Angkora",
      filterType: "battery",
      similarKey: "battery",
      icon: "battery",
      volume: "24L",
      title: "ឧបករណ៍បាតឺរី អង្គរា",
      description: "ម៉ូដែលកម្លាំងល្អ សម្រាប់ប្រព័ន្ធបាញ់ថ្នាំចល័ត និងការងារប្រភេទមធ្យម។",
      series: "Power Box",
      depoPrice: "$27.00",
      userPrice: "$39.00",
      stock: 7,
      artBg: "#f1fbf5",
      artColor: "#9bd6a9",
      colorGroup: "angkoraBattery",
      tags: ["battery", "angkora", "agt-24m", "24l", "portable", "power"],
    }),
    makeProduct({
      code: "AGT-30M",
      brand: "Angkora",
      filterType: "battery",
      similarKey: "battery",
      icon: "battery",
      volume: "30L",
      title: "ឧបករណ៍បាតឺរី អង្គរា",
      description: "សម្រាប់ការងារចល័តចំណុះធំ ដែលត្រូវការថាមពលមានស្ថេរភាព។",
      series: "Mobile Max",
      depoPrice: "$29.50",
      userPrice: "$43.00",
      stock: 4,
      featured: true,
      artBg: "#eef9ff",
      artColor: "#93c8df",
      colorGroup: "angkoraBattery",
      tags: ["featured", "battery", "angkora", "agt-30m", "30l", "portable", "max"],
    }),
    makeProduct({
      code: "AGT-30LR",
      brand: "Angkora",
      filterType: "battery",
      similarKey: "battery",
      icon: "battery",
      volume: "30L",
      title: "ឧបករណ៍បាតឺរីសាកថ្ម អង្គរា",
      description: "រចនាឡើងសម្រាប់ការប្រើប្រាស់យូរ និងងាយស្រួលថែទាំនៅក្នុងចម្ការ។",
      series: "Charge Max",
      depoPrice: "$31.00",
      userPrice: "$45.00",
      stock: 3,
      artBg: "#fff7ee",
      artColor: "#e9c089",
      colorGroup: "angkoraBattery",
      tags: ["battery", "angkora", "agt-30lr", "30l", "rechargeable", "max"],
    }),
    makeProduct({
      code: "NK-12L",
      brand: "Nikaza",
      filterType: "battery",
      similarKey: "battery",
      icon: "battery",
      volume: "12L",
      title: "ប្រអប់បាតឺរី នីកាហ្សា",
      description: "ប្រអប់បាតឺរីតូច សម្រាប់ប្រើជាមួយប្រព័ន្ធបាញ់ថ្នាំចល័ត។",
      series: "Lite Box",
      depoPrice: "$18.00",
      userPrice: "$26.00",
      stock: 17,
      artBg: "#eef1ff",
      artColor: "#a4b0eb",
      colorGroup: "nikazaBattery",
      tags: ["battery", "nikaza", "nk-12l", "12l", "power", "box"],
    }),
    makeProduct({
      code: "NK-16L",
      brand: "Nikaza",
      filterType: "battery",
      similarKey: "battery",
      icon: "battery",
      volume: "16L",
      title: "ប្រអប់បាតឺរី នីកាហ្សា",
      description: "ងាយស្រួលដឹកជញ្ជូន និងសមស្របសម្រាប់អ្នកប្រើប្រាស់នៅផ្ទៃដីតូច។",
      series: "Field Box",
      depoPrice: "$20.00",
      userPrice: "$29.00",
      stock: 13,
      artBg: "#f1fbf8",
      artColor: "#99d3b0",
      colorGroup: "nikazaBattery",
      tags: ["battery", "nikaza", "nk-16l", "16l", "portable", "field"],
    }),
    makeProduct({
      code: "NK-18LR",
      brand: "Nikaza",
      filterType: "battery",
      similarKey: "battery",
      icon: "battery",
      volume: "18L",
      title: "ប្រអប់បាតឺរីសាកថ្ម នីកាហ្សា",
      description: "សាកថ្មបានងាយ និងមានរាងតូចសមស្របសម្រាប់ការរៀបចំទុក។",
      series: "LR Compact",
      depoPrice: "$22.50",
      userPrice: "$32.00",
      stock: 6,
      artBg: "#f9eef5",
      artColor: "#df9dba",
      colorGroup: "nikazaBattery",
      tags: ["battery", "nikaza", "nk-18lr", "18l", "rechargeable", "compact"],
    }),
    makeProduct({
      code: "NK-24L",
      brand: "Nikaza",
      filterType: "battery",
      similarKey: "battery",
      icon: "battery",
      volume: "24L",
      title: "ប្រអប់បាតឺរី នីកាហ្សា",
      description: "បាតឺរីចល័តចំណុះមធ្យម សម្រាប់ការងារកសិកម្មប្រចាំថ្ងៃ។",
      series: "Power Field",
      depoPrice: "$24.00",
      userPrice: "$35.00",
      stock: 8,
      artBg: "#eef8ff",
      artColor: "#96c7e0",
      colorGroup: "nikazaBattery",
      tags: ["battery", "nikaza", "nk-24l", "24l", "power", "field"],
    }),
    makeProduct({
      code: "NK-30LR",
      brand: "Nikaza",
      filterType: "battery",
      similarKey: "battery",
      icon: "battery",
      volume: "30L",
      title: "ប្រអប់បាតឺរីសាកថ្ម នីកាហ្សា",
      description: "សម្រាប់ការងារចំណុះធំ និងផ្តល់ថាមពលបានយូរ សមស្របសម្រាប់អ្នកលក់។",
      series: "Charge Pro",
      depoPrice: "$28.50",
      userPrice: "$41.00",
      stock: 2,
      featured: true,
      artBg: "#fff8eb",
      artColor: "#e6c56f",
      colorGroup: "nikazaBattery",
      tags: ["featured", "battery", "nikaza", "nk-30lr", "30l", "rechargeable", "pro"],
    }),
    makeProduct({
      code: "SP-16L",
      brand: "Superbat",
      filterType: "battery",
      similarKey: "battery",
      icon: "battery",
      volume: "16L",
      title: "ឧបករណ៍បាតឺរី ស៊ុបឺបេត",
      description: "ម៉ូដែលស្រាល សម្រាប់ការងារចល័ត និងការប្រើប្រាស់លើផ្ទៃតូច។",
      series: "Super Lite",
      depoPrice: "$17.50",
      userPrice: "$25.00",
      stock: 19,
      artBg: "#fff9e7",
      artColor: "#e4c45e",
      colorGroup: "superbatBattery",
      tags: ["battery", "superbat", "sp-16l", "16l", "portable", "lite"],
    }),
    makeProduct({
      code: "SP-18L",
      brand: "Superbat",
      filterType: "battery",
      similarKey: "battery",
      icon: "battery",
      volume: "18L",
      title: "ឧបករណ៍បាតឺរី ស៊ុបឺបេត",
      description: "រឹងមាំ និងងាយស្រួលសាកថ្ម សម្រាប់ការងារប្រចាំថ្ងៃ។",
      series: "Super Charge",
      depoPrice: "$18.80",
      userPrice: "$27.50",
      stock: 15,
      artBg: "#fff8ec",
      artColor: "#e8bf72",
      colorGroup: "superbatBattery",
      tags: ["battery", "superbat", "sp-18l", "18l", "recharge", "charge"],
    }),
    makeProduct({
      code: "SP-22L",
      brand: "Superbat",
      filterType: "battery",
      similarKey: "battery",
      icon: "battery",
      volume: "22L",
      title: "ឧបករណ៍បាតឺរី ស៊ុបឺបេត",
      description: "សម្រាប់ប្រព័ន្ធបាញ់ថ្នាំចល័តដែលត្រូវការថាមពលមានស្ថេរភាព។",
      series: "Power Safe",
      depoPrice: "$20.50",
      userPrice: "$30.00",
      stock: 11,
      artBg: "#eef3ff",
      artColor: "#a2b0ef",
      colorGroup: "superbatBattery",
      tags: ["battery", "superbat", "sp-22l", "22l", "power", "safe"],
    }),
    makeProduct({
      code: "SP-24L",
      brand: "Superbat",
      filterType: "battery",
      similarKey: "battery",
      icon: "battery",
      volume: "24L",
      title: "ឧបករណ៍បាតឺរី ស៊ុបឺបេត",
      description: "ចំណុះធំជាងមុន សម្រាប់ការងារដែលត្រូវការថាមពលបន្តបន្ទាប់។",
      series: "Super Max",
      depoPrice: "$22.00",
      userPrice: "$32.00",
      stock: 8,
      featured: true,
      artBg: "#eef9ff",
      artColor: "#91c4e3",
      colorGroup: "superbatBattery",
      tags: ["featured", "battery", "superbat", "sp-24l", "24l", "super", "max"],
    }),
    makeProduct({
      code: "NK-8100",
      brand: "Nikaza",
      filterType: "sprayer",
      similarKey: "mister",
      icon: "mister",
      volume: "Pro",
      title: "ម៉ាស៊ីនបាញ់អ័ព្ទ នីកាហ្សា",
      description: "សម្រាប់បាញ់ផ្សាយបានទូលំទូលាយ និងងាយប្រើនៅកន្លែងការងារដែលមានចន្លោះតូច។",
      series: "Mist Pro",
      depoPrice: "$85.00",
      userPrice: "$113.00",
      stock: 4,
      featured: true,
      artBg: "#f1f9f4",
      artColor: "#9fd6ad",
      colorGroup: "mister",
      sizes: ["Pro", "បាញ់អ័ព្ទ"],
      tags: ["featured", "sprayer", "nikaza", "nk-8100", "mister", "pro"],
    }),
  ];

  window.catalogProducts = products;
})();
